/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendorSlugRouteImport } from './routes/vendor.$slug'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedReferralsRouteImport } from './routes/_authenticated/referrals'
import { Route as AuthenticatedPersonalInfoRouteImport } from './routes/_authenticated/personal-info'
import { Route as AuthenticatedPaymentMethodsRouteImport } from './routes/_authenticated/payment-methods'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedHelpRouteImport } from './routes/_authenticated/help'
import { Route as AuthenticatedGroceriesRouteImport } from './routes/_authenticated/groceries'
import { Route as AuthenticatedDiscoverRouteImport } from './routes/_authenticated/discover'
import { Route as AuthenticatedCartRouteImport } from './routes/_authenticated/cart'
import { Route as AuthenticatedBookRouteImport } from './routes/_authenticated/book'
import { Route as AuthenticatedAddressesRouteImport } from './routes/_authenticated/addresses'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats.index'
import { Route as ApiWebhooksStripeRouteImport } from './routes/api/webhooks/stripe'
import { Route as ApiWebhooksPaystackRouteImport } from './routes/api/webhooks/paystack'
import { Route as AuthenticatedWalletTopUpRouteImport } from './routes/_authenticated/wallet.top-up'
import { Route as AuthenticatedWalletSendRouteImport } from './routes/_authenticated/wallet.send'
import { Route as AuthenticatedWalletRequestRouteImport } from './routes/_authenticated/wallet.request'
import { Route as AuthenticatedVendorShopsRouteImport } from './routes/_authenticated/vendor.shops'
import { Route as AuthenticatedVendorProfileRouteImport } from './routes/_authenticated/vendor.profile'
import { Route as AuthenticatedVendorOrdersRouteImport } from './routes/_authenticated/vendor.orders'
import { Route as AuthenticatedVendorMessagesRouteImport } from './routes/_authenticated/vendor.messages'
import { Route as AuthenticatedVendorMenuRouteImport } from './routes/_authenticated/vendor.menu'
import { Route as AuthenticatedVendorEarningsRouteImport } from './routes/_authenticated/vendor.earnings'
import { Route as AuthenticatedVendorDashboardRouteImport } from './routes/_authenticated/vendor.dashboard'
import { Route as AuthenticatedRiderEarningsRouteImport } from './routes/_authenticated/rider.earnings'
import { Route as AuthenticatedRiderDocumentsRouteImport } from './routes/_authenticated/rider.documents'
import { Route as AuthenticatedRiderDashboardRouteImport } from './routes/_authenticated/rider.dashboard'
import { Route as AuthenticatedRiderAvailableRouteImport } from './routes/_authenticated/rider.available'
import { Route as AuthenticatedOrdersOrderIdRouteImport } from './routes/_authenticated/orders.$orderId'
import { Route as AuthenticatedChatsVendorIdRouteImport } from './routes/_authenticated/chats.$vendorId'
import { Route as AuthenticatedAdminWebshopRouteImport } from './routes/_authenticated/admin.webshop'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminSuccessRouteImport } from './routes/_authenticated/admin.success'
import { Route as AuthenticatedAdminStoresRouteImport } from './routes/_authenticated/admin.stores'
import { Route as AuthenticatedAdminStoreGroupsRouteImport } from './routes/_authenticated/admin.store-groups'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminSalesRouteImport } from './routes/_authenticated/admin.sales'
import { Route as AuthenticatedAdminRidersRouteImport } from './routes/_authenticated/admin.riders'
import { Route as AuthenticatedAdminReviewsRouteImport } from './routes/_authenticated/admin.reviews'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin.reports'
import { Route as AuthenticatedAdminProfileRouteImport } from './routes/_authenticated/admin.profile'
import { Route as AuthenticatedAdminPrepTimesRouteImport } from './routes/_authenticated/admin.prep-times'
import { Route as AuthenticatedAdminPerformanceRouteImport } from './routes/_authenticated/admin.performance'
import { Route as AuthenticatedAdminPayoutsOrdersRouteImport } from './routes/_authenticated/admin.payouts-orders'
import { Route as AuthenticatedAdminPayoutsRouteImport } from './routes/_authenticated/admin.payouts'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin.payments'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/admin.orders'
import { Route as AuthenticatedAdminOperationsRouteImport } from './routes/_authenticated/admin.operations'
import { Route as AuthenticatedAdminOffersRouteImport } from './routes/_authenticated/admin.offers'
import { Route as AuthenticatedAdminMenuRouteImport } from './routes/_authenticated/admin.menu'
import { Route as AuthenticatedAdminMarketingRouteImport } from './routes/_authenticated/admin.marketing'
import { Route as AuthenticatedAdminInvoicesRouteImport } from './routes/_authenticated/admin.invoices'
import { Route as AuthenticatedAdminInvoiceSettingsRouteImport } from './routes/_authenticated/admin.invoice-settings'
import { Route as AuthenticatedAdminHolidayHoursRouteImport } from './routes/_authenticated/admin.holiday-hours'
import { Route as AuthenticatedAdminGeneralRouteImport } from './routes/_authenticated/admin.general'
import { Route as AuthenticatedAdminFinancingRouteImport } from './routes/_authenticated/admin.financing'
import { Route as AuthenticatedAdminDocumentsRouteImport } from './routes/_authenticated/admin.documents'
import { Route as AuthenticatedAdminDevicesRouteImport } from './routes/_authenticated/admin.devices'
import { Route as AuthenticatedAdminDeliveryRouteImport } from './routes/_authenticated/admin.delivery'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin.dashboard'
import { Route as AuthenticatedAdminCustomersRouteImport } from './routes/_authenticated/admin.customers'
import { Route as AuthenticatedAdminCustomerInsightsRouteImport } from './routes/_authenticated/admin.customer-insights'
import { Route as AuthenticatedAdminBankingRouteImport } from './routes/_authenticated/admin.banking'
import { Route as AuthenticatedAdminAdsRouteImport } from './routes/_authenticated/admin.ads'
import { Route as VendorSlugItemItemIdRouteImport } from './routes/vendor.$slug.item.$itemId'
import { Route as AuthenticatedVendorMessagesConversationIdRouteImport } from './routes/_authenticated/vendor.messages.$conversationId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorSlugRoute = VendorSlugRouteImport.update({
  id: '/vendor/$slug',
  path: '/vendor/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReferralsRoute = AuthenticatedReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPersonalInfoRoute =
  AuthenticatedPersonalInfoRouteImport.update({
    id: '/personal-info',
    path: '/personal-info',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPaymentMethodsRoute =
  AuthenticatedPaymentMethodsRouteImport.update({
    id: '/payment-methods',
    path: '/payment-methods',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpRoute = AuthenticatedHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGroceriesRoute = AuthenticatedGroceriesRouteImport.update({
  id: '/groceries',
  path: '/groceries',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiscoverRoute = AuthenticatedDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCartRoute = AuthenticatedCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBookRoute = AuthenticatedBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAddressesRoute = AuthenticatedAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiWebhooksStripeRoute = ApiWebhooksStripeRouteImport.update({
  id: '/api/webhooks/stripe',
  path: '/api/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksPaystackRoute = ApiWebhooksPaystackRouteImport.update({
  id: '/api/webhooks/paystack',
  path: '/api/webhooks/paystack',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWalletTopUpRoute =
  AuthenticatedWalletTopUpRouteImport.update({
    id: '/top-up',
    path: '/top-up',
    getParentRoute: () => AuthenticatedWalletRoute,
  } as any)
const AuthenticatedWalletSendRoute = AuthenticatedWalletSendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => AuthenticatedWalletRoute,
} as any)
const AuthenticatedWalletRequestRoute =
  AuthenticatedWalletRequestRouteImport.update({
    id: '/request',
    path: '/request',
    getParentRoute: () => AuthenticatedWalletRoute,
  } as any)
const AuthenticatedVendorShopsRoute =
  AuthenticatedVendorShopsRouteImport.update({
    id: '/vendor/shops',
    path: '/vendor/shops',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendorProfileRoute =
  AuthenticatedVendorProfileRouteImport.update({
    id: '/vendor/profile',
    path: '/vendor/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendorOrdersRoute =
  AuthenticatedVendorOrdersRouteImport.update({
    id: '/vendor/orders',
    path: '/vendor/orders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendorMessagesRoute =
  AuthenticatedVendorMessagesRouteImport.update({
    id: '/vendor/messages',
    path: '/vendor/messages',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendorMenuRoute = AuthenticatedVendorMenuRouteImport.update({
  id: '/vendor/menu',
  path: '/vendor/menu',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVendorEarningsRoute =
  AuthenticatedVendorEarningsRouteImport.update({
    id: '/vendor/earnings',
    path: '/vendor/earnings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendorDashboardRoute =
  AuthenticatedVendorDashboardRouteImport.update({
    id: '/vendor/dashboard',
    path: '/vendor/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRiderEarningsRoute =
  AuthenticatedRiderEarningsRouteImport.update({
    id: '/rider/earnings',
    path: '/rider/earnings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRiderDocumentsRoute =
  AuthenticatedRiderDocumentsRouteImport.update({
    id: '/rider/documents',
    path: '/rider/documents',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRiderDashboardRoute =
  AuthenticatedRiderDashboardRouteImport.update({
    id: '/rider/dashboard',
    path: '/rider/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRiderAvailableRoute =
  AuthenticatedRiderAvailableRouteImport.update({
    id: '/rider/available',
    path: '/rider/available',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersOrderIdRoute =
  AuthenticatedOrdersOrderIdRouteImport.update({
    id: '/$orderId',
    path: '/$orderId',
    getParentRoute: () => AuthenticatedOrdersRoute,
  } as any)
const AuthenticatedChatsVendorIdRoute =
  AuthenticatedChatsVendorIdRouteImport.update({
    id: '/chats/$vendorId',
    path: '/chats/$vendorId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminWebshopRoute =
  AuthenticatedAdminWebshopRouteImport.update({
    id: '/admin/webshop',
    path: '/admin/webshop',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminSuccessRoute =
  AuthenticatedAdminSuccessRouteImport.update({
    id: '/admin/success',
    path: '/admin/success',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminStoresRoute =
  AuthenticatedAdminStoresRouteImport.update({
    id: '/admin/stores',
    path: '/admin/stores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminStoreGroupsRoute =
  AuthenticatedAdminStoreGroupsRouteImport.update({
    id: '/admin/store-groups',
    path: '/admin/store-groups',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSalesRoute = AuthenticatedAdminSalesRouteImport.update({
  id: '/admin/sales',
  path: '/admin/sales',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRidersRoute =
  AuthenticatedAdminRidersRouteImport.update({
    id: '/admin/riders',
    path: '/admin/riders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminReviewsRoute =
  AuthenticatedAdminReviewsRouteImport.update({
    id: '/admin/reviews',
    path: '/admin/reviews',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/admin/reports',
    path: '/admin/reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminProfileRoute =
  AuthenticatedAdminProfileRouteImport.update({
    id: '/admin/profile',
    path: '/admin/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPrepTimesRoute =
  AuthenticatedAdminPrepTimesRouteImport.update({
    id: '/admin/prep-times',
    path: '/admin/prep-times',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPerformanceRoute =
  AuthenticatedAdminPerformanceRouteImport.update({
    id: '/admin/performance',
    path: '/admin/performance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPayoutsOrdersRoute =
  AuthenticatedAdminPayoutsOrdersRouteImport.update({
    id: '/admin/payouts-orders',
    path: '/admin/payouts-orders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPayoutsRoute =
  AuthenticatedAdminPayoutsRouteImport.update({
    id: '/admin/payouts',
    path: '/admin/payouts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/admin/payments',
    path: '/admin/payments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/admin/orders',
    path: '/admin/orders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminOperationsRoute =
  AuthenticatedAdminOperationsRouteImport.update({
    id: '/admin/operations',
    path: '/admin/operations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminOffersRoute =
  AuthenticatedAdminOffersRouteImport.update({
    id: '/admin/offers',
    path: '/admin/offers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminMenuRoute = AuthenticatedAdminMenuRouteImport.update({
  id: '/admin/menu',
  path: '/admin/menu',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminMarketingRoute =
  AuthenticatedAdminMarketingRouteImport.update({
    id: '/admin/marketing',
    path: '/admin/marketing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminInvoicesRoute =
  AuthenticatedAdminInvoicesRouteImport.update({
    id: '/admin/invoices',
    path: '/admin/invoices',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminInvoiceSettingsRoute =
  AuthenticatedAdminInvoiceSettingsRouteImport.update({
    id: '/admin/invoice-settings',
    path: '/admin/invoice-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminHolidayHoursRoute =
  AuthenticatedAdminHolidayHoursRouteImport.update({
    id: '/admin/holiday-hours',
    path: '/admin/holiday-hours',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminGeneralRoute =
  AuthenticatedAdminGeneralRouteImport.update({
    id: '/admin/general',
    path: '/admin/general',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminFinancingRoute =
  AuthenticatedAdminFinancingRouteImport.update({
    id: '/admin/financing',
    path: '/admin/financing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDocumentsRoute =
  AuthenticatedAdminDocumentsRouteImport.update({
    id: '/admin/documents',
    path: '/admin/documents',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDevicesRoute =
  AuthenticatedAdminDevicesRouteImport.update({
    id: '/admin/devices',
    path: '/admin/devices',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDeliveryRoute =
  AuthenticatedAdminDeliveryRouteImport.update({
    id: '/admin/delivery',
    path: '/admin/delivery',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/admin/dashboard',
    path: '/admin/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCustomersRoute =
  AuthenticatedAdminCustomersRouteImport.update({
    id: '/admin/customers',
    path: '/admin/customers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCustomerInsightsRoute =
  AuthenticatedAdminCustomerInsightsRouteImport.update({
    id: '/admin/customer-insights',
    path: '/admin/customer-insights',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminBankingRoute =
  AuthenticatedAdminBankingRouteImport.update({
    id: '/admin/banking',
    path: '/admin/banking',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAdsRoute = AuthenticatedAdminAdsRouteImport.update({
  id: '/admin/ads',
  path: '/admin/ads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const VendorSlugItemItemIdRoute = VendorSlugItemItemIdRouteImport.update({
  id: '/item/$itemId',
  path: '/item/$itemId',
  getParentRoute: () => VendorSlugRoute,
} as any)
const AuthenticatedVendorMessagesConversationIdRoute =
  AuthenticatedVendorMessagesConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => AuthenticatedVendorMessagesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account': typeof AuthenticatedAccountRoute
  '/addresses': typeof AuthenticatedAddressesRoute
  '/book': typeof AuthenticatedBookRoute
  '/cart': typeof AuthenticatedCartRoute
  '/discover': typeof AuthenticatedDiscoverRoute
  '/groceries': typeof AuthenticatedGroceriesRoute
  '/help': typeof AuthenticatedHelpRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/orders': typeof AuthenticatedOrdersRouteWithChildren
  '/payment-methods': typeof AuthenticatedPaymentMethodsRoute
  '/personal-info': typeof AuthenticatedPersonalInfoRoute
  '/referrals': typeof AuthenticatedReferralsRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/wallet': typeof AuthenticatedWalletRouteWithChildren
  '/vendor/$slug': typeof VendorSlugRouteWithChildren
  '/admin/ads': typeof AuthenticatedAdminAdsRoute
  '/admin/banking': typeof AuthenticatedAdminBankingRoute
  '/admin/customer-insights': typeof AuthenticatedAdminCustomerInsightsRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/delivery': typeof AuthenticatedAdminDeliveryRoute
  '/admin/devices': typeof AuthenticatedAdminDevicesRoute
  '/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/admin/financing': typeof AuthenticatedAdminFinancingRoute
  '/admin/general': typeof AuthenticatedAdminGeneralRoute
  '/admin/holiday-hours': typeof AuthenticatedAdminHolidayHoursRoute
  '/admin/invoice-settings': typeof AuthenticatedAdminInvoiceSettingsRoute
  '/admin/invoices': typeof AuthenticatedAdminInvoicesRoute
  '/admin/marketing': typeof AuthenticatedAdminMarketingRoute
  '/admin/menu': typeof AuthenticatedAdminMenuRoute
  '/admin/offers': typeof AuthenticatedAdminOffersRoute
  '/admin/operations': typeof AuthenticatedAdminOperationsRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/payouts': typeof AuthenticatedAdminPayoutsRoute
  '/admin/payouts-orders': typeof AuthenticatedAdminPayoutsOrdersRoute
  '/admin/performance': typeof AuthenticatedAdminPerformanceRoute
  '/admin/prep-times': typeof AuthenticatedAdminPrepTimesRoute
  '/admin/profile': typeof AuthenticatedAdminProfileRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/admin/riders': typeof AuthenticatedAdminRidersRoute
  '/admin/sales': typeof AuthenticatedAdminSalesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/store-groups': typeof AuthenticatedAdminStoreGroupsRoute
  '/admin/stores': typeof AuthenticatedAdminStoresRoute
  '/admin/success': typeof AuthenticatedAdminSuccessRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/webshop': typeof AuthenticatedAdminWebshopRoute
  '/chats/$vendorId': typeof AuthenticatedChatsVendorIdRoute
  '/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/rider/available': typeof AuthenticatedRiderAvailableRoute
  '/rider/dashboard': typeof AuthenticatedRiderDashboardRoute
  '/rider/documents': typeof AuthenticatedRiderDocumentsRoute
  '/rider/earnings': typeof AuthenticatedRiderEarningsRoute
  '/vendor/dashboard': typeof AuthenticatedVendorDashboardRoute
  '/vendor/earnings': typeof AuthenticatedVendorEarningsRoute
  '/vendor/menu': typeof AuthenticatedVendorMenuRoute
  '/vendor/messages': typeof AuthenticatedVendorMessagesRouteWithChildren
  '/vendor/orders': typeof AuthenticatedVendorOrdersRoute
  '/vendor/profile': typeof AuthenticatedVendorProfileRoute
  '/vendor/shops': typeof AuthenticatedVendorShopsRoute
  '/wallet/request': typeof AuthenticatedWalletRequestRoute
  '/wallet/send': typeof AuthenticatedWalletSendRoute
  '/wallet/top-up': typeof AuthenticatedWalletTopUpRoute
  '/api/webhooks/paystack': typeof ApiWebhooksPaystackRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/chats/': typeof AuthenticatedChatsIndexRoute
  '/vendor/messages/$conversationId': typeof AuthenticatedVendorMessagesConversationIdRoute
  '/vendor/$slug/item/$itemId': typeof VendorSlugItemItemIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account': typeof AuthenticatedAccountRoute
  '/addresses': typeof AuthenticatedAddressesRoute
  '/book': typeof AuthenticatedBookRoute
  '/cart': typeof AuthenticatedCartRoute
  '/discover': typeof AuthenticatedDiscoverRoute
  '/groceries': typeof AuthenticatedGroceriesRoute
  '/help': typeof AuthenticatedHelpRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/orders': typeof AuthenticatedOrdersRouteWithChildren
  '/payment-methods': typeof AuthenticatedPaymentMethodsRoute
  '/personal-info': typeof AuthenticatedPersonalInfoRoute
  '/referrals': typeof AuthenticatedReferralsRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/wallet': typeof AuthenticatedWalletRouteWithChildren
  '/vendor/$slug': typeof VendorSlugRouteWithChildren
  '/admin/ads': typeof AuthenticatedAdminAdsRoute
  '/admin/banking': typeof AuthenticatedAdminBankingRoute
  '/admin/customer-insights': typeof AuthenticatedAdminCustomerInsightsRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/delivery': typeof AuthenticatedAdminDeliveryRoute
  '/admin/devices': typeof AuthenticatedAdminDevicesRoute
  '/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/admin/financing': typeof AuthenticatedAdminFinancingRoute
  '/admin/general': typeof AuthenticatedAdminGeneralRoute
  '/admin/holiday-hours': typeof AuthenticatedAdminHolidayHoursRoute
  '/admin/invoice-settings': typeof AuthenticatedAdminInvoiceSettingsRoute
  '/admin/invoices': typeof AuthenticatedAdminInvoicesRoute
  '/admin/marketing': typeof AuthenticatedAdminMarketingRoute
  '/admin/menu': typeof AuthenticatedAdminMenuRoute
  '/admin/offers': typeof AuthenticatedAdminOffersRoute
  '/admin/operations': typeof AuthenticatedAdminOperationsRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/payouts': typeof AuthenticatedAdminPayoutsRoute
  '/admin/payouts-orders': typeof AuthenticatedAdminPayoutsOrdersRoute
  '/admin/performance': typeof AuthenticatedAdminPerformanceRoute
  '/admin/prep-times': typeof AuthenticatedAdminPrepTimesRoute
  '/admin/profile': typeof AuthenticatedAdminProfileRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/admin/riders': typeof AuthenticatedAdminRidersRoute
  '/admin/sales': typeof AuthenticatedAdminSalesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/store-groups': typeof AuthenticatedAdminStoreGroupsRoute
  '/admin/stores': typeof AuthenticatedAdminStoresRoute
  '/admin/success': typeof AuthenticatedAdminSuccessRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/webshop': typeof AuthenticatedAdminWebshopRoute
  '/chats/$vendorId': typeof AuthenticatedChatsVendorIdRoute
  '/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/rider/available': typeof AuthenticatedRiderAvailableRoute
  '/rider/dashboard': typeof AuthenticatedRiderDashboardRoute
  '/rider/documents': typeof AuthenticatedRiderDocumentsRoute
  '/rider/earnings': typeof AuthenticatedRiderEarningsRoute
  '/vendor/dashboard': typeof AuthenticatedVendorDashboardRoute
  '/vendor/earnings': typeof AuthenticatedVendorEarningsRoute
  '/vendor/menu': typeof AuthenticatedVendorMenuRoute
  '/vendor/messages': typeof AuthenticatedVendorMessagesRouteWithChildren
  '/vendor/orders': typeof AuthenticatedVendorOrdersRoute
  '/vendor/profile': typeof AuthenticatedVendorProfileRoute
  '/vendor/shops': typeof AuthenticatedVendorShopsRoute
  '/wallet/request': typeof AuthenticatedWalletRequestRoute
  '/wallet/send': typeof AuthenticatedWalletSendRoute
  '/wallet/top-up': typeof AuthenticatedWalletTopUpRoute
  '/api/webhooks/paystack': typeof ApiWebhooksPaystackRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/vendor/messages/$conversationId': typeof AuthenticatedVendorMessagesConversationIdRoute
  '/vendor/$slug/item/$itemId': typeof VendorSlugItemItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/addresses': typeof AuthenticatedAddressesRoute
  '/_authenticated/book': typeof AuthenticatedBookRoute
  '/_authenticated/cart': typeof AuthenticatedCartRoute
  '/_authenticated/discover': typeof AuthenticatedDiscoverRoute
  '/_authenticated/groceries': typeof AuthenticatedGroceriesRoute
  '/_authenticated/help': typeof AuthenticatedHelpRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRouteWithChildren
  '/_authenticated/payment-methods': typeof AuthenticatedPaymentMethodsRoute
  '/_authenticated/personal-info': typeof AuthenticatedPersonalInfoRoute
  '/_authenticated/referrals': typeof AuthenticatedReferralsRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRouteWithChildren
  '/vendor/$slug': typeof VendorSlugRouteWithChildren
  '/_authenticated/admin/ads': typeof AuthenticatedAdminAdsRoute
  '/_authenticated/admin/banking': typeof AuthenticatedAdminBankingRoute
  '/_authenticated/admin/customer-insights': typeof AuthenticatedAdminCustomerInsightsRoute
  '/_authenticated/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/delivery': typeof AuthenticatedAdminDeliveryRoute
  '/_authenticated/admin/devices': typeof AuthenticatedAdminDevicesRoute
  '/_authenticated/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/_authenticated/admin/financing': typeof AuthenticatedAdminFinancingRoute
  '/_authenticated/admin/general': typeof AuthenticatedAdminGeneralRoute
  '/_authenticated/admin/holiday-hours': typeof AuthenticatedAdminHolidayHoursRoute
  '/_authenticated/admin/invoice-settings': typeof AuthenticatedAdminInvoiceSettingsRoute
  '/_authenticated/admin/invoices': typeof AuthenticatedAdminInvoicesRoute
  '/_authenticated/admin/marketing': typeof AuthenticatedAdminMarketingRoute
  '/_authenticated/admin/menu': typeof AuthenticatedAdminMenuRoute
  '/_authenticated/admin/offers': typeof AuthenticatedAdminOffersRoute
  '/_authenticated/admin/operations': typeof AuthenticatedAdminOperationsRoute
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/payouts': typeof AuthenticatedAdminPayoutsRoute
  '/_authenticated/admin/payouts-orders': typeof AuthenticatedAdminPayoutsOrdersRoute
  '/_authenticated/admin/performance': typeof AuthenticatedAdminPerformanceRoute
  '/_authenticated/admin/prep-times': typeof AuthenticatedAdminPrepTimesRoute
  '/_authenticated/admin/profile': typeof AuthenticatedAdminProfileRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/_authenticated/admin/riders': typeof AuthenticatedAdminRidersRoute
  '/_authenticated/admin/sales': typeof AuthenticatedAdminSalesRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/store-groups': typeof AuthenticatedAdminStoreGroupsRoute
  '/_authenticated/admin/stores': typeof AuthenticatedAdminStoresRoute
  '/_authenticated/admin/success': typeof AuthenticatedAdminSuccessRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/webshop': typeof AuthenticatedAdminWebshopRoute
  '/_authenticated/chats/$vendorId': typeof AuthenticatedChatsVendorIdRoute
  '/_authenticated/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/_authenticated/rider/available': typeof AuthenticatedRiderAvailableRoute
  '/_authenticated/rider/dashboard': typeof AuthenticatedRiderDashboardRoute
  '/_authenticated/rider/documents': typeof AuthenticatedRiderDocumentsRoute
  '/_authenticated/rider/earnings': typeof AuthenticatedRiderEarningsRoute
  '/_authenticated/vendor/dashboard': typeof AuthenticatedVendorDashboardRoute
  '/_authenticated/vendor/earnings': typeof AuthenticatedVendorEarningsRoute
  '/_authenticated/vendor/menu': typeof AuthenticatedVendorMenuRoute
  '/_authenticated/vendor/messages': typeof AuthenticatedVendorMessagesRouteWithChildren
  '/_authenticated/vendor/orders': typeof AuthenticatedVendorOrdersRoute
  '/_authenticated/vendor/profile': typeof AuthenticatedVendorProfileRoute
  '/_authenticated/vendor/shops': typeof AuthenticatedVendorShopsRoute
  '/_authenticated/wallet/request': typeof AuthenticatedWalletRequestRoute
  '/_authenticated/wallet/send': typeof AuthenticatedWalletSendRoute
  '/_authenticated/wallet/top-up': typeof AuthenticatedWalletTopUpRoute
  '/api/webhooks/paystack': typeof ApiWebhooksPaystackRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/vendor/messages/$conversationId': typeof AuthenticatedVendorMessagesConversationIdRoute
  '/vendor/$slug/item/$itemId': typeof VendorSlugItemItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/account'
    | '/addresses'
    | '/book'
    | '/cart'
    | '/discover'
    | '/groceries'
    | '/help'
    | '/notifications'
    | '/orders'
    | '/payment-methods'
    | '/personal-info'
    | '/referrals'
    | '/search'
    | '/settings'
    | '/wallet'
    | '/vendor/$slug'
    | '/admin/ads'
    | '/admin/banking'
    | '/admin/customer-insights'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/delivery'
    | '/admin/devices'
    | '/admin/documents'
    | '/admin/financing'
    | '/admin/general'
    | '/admin/holiday-hours'
    | '/admin/invoice-settings'
    | '/admin/invoices'
    | '/admin/marketing'
    | '/admin/menu'
    | '/admin/offers'
    | '/admin/operations'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/payouts'
    | '/admin/payouts-orders'
    | '/admin/performance'
    | '/admin/prep-times'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/riders'
    | '/admin/sales'
    | '/admin/settings'
    | '/admin/store-groups'
    | '/admin/stores'
    | '/admin/success'
    | '/admin/users'
    | '/admin/webshop'
    | '/chats/$vendorId'
    | '/orders/$orderId'
    | '/rider/available'
    | '/rider/dashboard'
    | '/rider/documents'
    | '/rider/earnings'
    | '/vendor/dashboard'
    | '/vendor/earnings'
    | '/vendor/menu'
    | '/vendor/messages'
    | '/vendor/orders'
    | '/vendor/profile'
    | '/vendor/shops'
    | '/wallet/request'
    | '/wallet/send'
    | '/wallet/top-up'
    | '/api/webhooks/paystack'
    | '/api/webhooks/stripe'
    | '/chats/'
    | '/vendor/messages/$conversationId'
    | '/vendor/$slug/item/$itemId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/account'
    | '/addresses'
    | '/book'
    | '/cart'
    | '/discover'
    | '/groceries'
    | '/help'
    | '/notifications'
    | '/orders'
    | '/payment-methods'
    | '/personal-info'
    | '/referrals'
    | '/search'
    | '/settings'
    | '/wallet'
    | '/vendor/$slug'
    | '/admin/ads'
    | '/admin/banking'
    | '/admin/customer-insights'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/delivery'
    | '/admin/devices'
    | '/admin/documents'
    | '/admin/financing'
    | '/admin/general'
    | '/admin/holiday-hours'
    | '/admin/invoice-settings'
    | '/admin/invoices'
    | '/admin/marketing'
    | '/admin/menu'
    | '/admin/offers'
    | '/admin/operations'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/payouts'
    | '/admin/payouts-orders'
    | '/admin/performance'
    | '/admin/prep-times'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/riders'
    | '/admin/sales'
    | '/admin/settings'
    | '/admin/store-groups'
    | '/admin/stores'
    | '/admin/success'
    | '/admin/users'
    | '/admin/webshop'
    | '/chats/$vendorId'
    | '/orders/$orderId'
    | '/rider/available'
    | '/rider/dashboard'
    | '/rider/documents'
    | '/rider/earnings'
    | '/vendor/dashboard'
    | '/vendor/earnings'
    | '/vendor/menu'
    | '/vendor/messages'
    | '/vendor/orders'
    | '/vendor/profile'
    | '/vendor/shops'
    | '/wallet/request'
    | '/wallet/send'
    | '/wallet/top-up'
    | '/api/webhooks/paystack'
    | '/api/webhooks/stripe'
    | '/chats'
    | '/vendor/messages/$conversationId'
    | '/vendor/$slug/item/$itemId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/account'
    | '/_authenticated/addresses'
    | '/_authenticated/book'
    | '/_authenticated/cart'
    | '/_authenticated/discover'
    | '/_authenticated/groceries'
    | '/_authenticated/help'
    | '/_authenticated/notifications'
    | '/_authenticated/orders'
    | '/_authenticated/payment-methods'
    | '/_authenticated/personal-info'
    | '/_authenticated/referrals'
    | '/_authenticated/search'
    | '/_authenticated/settings'
    | '/_authenticated/wallet'
    | '/vendor/$slug'
    | '/_authenticated/admin/ads'
    | '/_authenticated/admin/banking'
    | '/_authenticated/admin/customer-insights'
    | '/_authenticated/admin/customers'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/delivery'
    | '/_authenticated/admin/devices'
    | '/_authenticated/admin/documents'
    | '/_authenticated/admin/financing'
    | '/_authenticated/admin/general'
    | '/_authenticated/admin/holiday-hours'
    | '/_authenticated/admin/invoice-settings'
    | '/_authenticated/admin/invoices'
    | '/_authenticated/admin/marketing'
    | '/_authenticated/admin/menu'
    | '/_authenticated/admin/offers'
    | '/_authenticated/admin/operations'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/payouts'
    | '/_authenticated/admin/payouts-orders'
    | '/_authenticated/admin/performance'
    | '/_authenticated/admin/prep-times'
    | '/_authenticated/admin/profile'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/reviews'
    | '/_authenticated/admin/riders'
    | '/_authenticated/admin/sales'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/store-groups'
    | '/_authenticated/admin/stores'
    | '/_authenticated/admin/success'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/webshop'
    | '/_authenticated/chats/$vendorId'
    | '/_authenticated/orders/$orderId'
    | '/_authenticated/rider/available'
    | '/_authenticated/rider/dashboard'
    | '/_authenticated/rider/documents'
    | '/_authenticated/rider/earnings'
    | '/_authenticated/vendor/dashboard'
    | '/_authenticated/vendor/earnings'
    | '/_authenticated/vendor/menu'
    | '/_authenticated/vendor/messages'
    | '/_authenticated/vendor/orders'
    | '/_authenticated/vendor/profile'
    | '/_authenticated/vendor/shops'
    | '/_authenticated/wallet/request'
    | '/_authenticated/wallet/send'
    | '/_authenticated/wallet/top-up'
    | '/api/webhooks/paystack'
    | '/api/webhooks/stripe'
    | '/_authenticated/chats/'
    | '/_authenticated/vendor/messages/$conversationId'
    | '/vendor/$slug/item/$itemId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VendorSlugRoute: typeof VendorSlugRouteWithChildren
  ApiWebhooksPaystackRoute: typeof ApiWebhooksPaystackRoute
  ApiWebhooksStripeRoute: typeof ApiWebhooksStripeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/$slug': {
      id: '/vendor/$slug'
      path: '/vendor/$slug'
      fullPath: '/vendor/$slug'
      preLoaderRoute: typeof VendorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/referrals': {
      id: '/_authenticated/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof AuthenticatedReferralsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/personal-info': {
      id: '/_authenticated/personal-info'
      path: '/personal-info'
      fullPath: '/personal-info'
      preLoaderRoute: typeof AuthenticatedPersonalInfoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payment-methods': {
      id: '/_authenticated/payment-methods'
      path: '/payment-methods'
      fullPath: '/payment-methods'
      preLoaderRoute: typeof AuthenticatedPaymentMethodsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help': {
      id: '/_authenticated/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AuthenticatedHelpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/groceries': {
      id: '/_authenticated/groceries'
      path: '/groceries'
      fullPath: '/groceries'
      preLoaderRoute: typeof AuthenticatedGroceriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/discover': {
      id: '/_authenticated/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AuthenticatedDiscoverRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cart': {
      id: '/_authenticated/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof AuthenticatedCartRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/book': {
      id: '/_authenticated/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof AuthenticatedBookRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/addresses': {
      id: '/_authenticated/addresses'
      path: '/addresses'
      fullPath: '/addresses'
      preLoaderRoute: typeof AuthenticatedAddressesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats/'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/webhooks/stripe': {
      id: '/api/webhooks/stripe'
      path: '/api/webhooks/stripe'
      fullPath: '/api/webhooks/stripe'
      preLoaderRoute: typeof ApiWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/paystack': {
      id: '/api/webhooks/paystack'
      path: '/api/webhooks/paystack'
      fullPath: '/api/webhooks/paystack'
      preLoaderRoute: typeof ApiWebhooksPaystackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wallet/top-up': {
      id: '/_authenticated/wallet/top-up'
      path: '/top-up'
      fullPath: '/wallet/top-up'
      preLoaderRoute: typeof AuthenticatedWalletTopUpRouteImport
      parentRoute: typeof AuthenticatedWalletRoute
    }
    '/_authenticated/wallet/send': {
      id: '/_authenticated/wallet/send'
      path: '/send'
      fullPath: '/wallet/send'
      preLoaderRoute: typeof AuthenticatedWalletSendRouteImport
      parentRoute: typeof AuthenticatedWalletRoute
    }
    '/_authenticated/wallet/request': {
      id: '/_authenticated/wallet/request'
      path: '/request'
      fullPath: '/wallet/request'
      preLoaderRoute: typeof AuthenticatedWalletRequestRouteImport
      parentRoute: typeof AuthenticatedWalletRoute
    }
    '/_authenticated/vendor/shops': {
      id: '/_authenticated/vendor/shops'
      path: '/vendor/shops'
      fullPath: '/vendor/shops'
      preLoaderRoute: typeof AuthenticatedVendorShopsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendor/profile': {
      id: '/_authenticated/vendor/profile'
      path: '/vendor/profile'
      fullPath: '/vendor/profile'
      preLoaderRoute: typeof AuthenticatedVendorProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendor/orders': {
      id: '/_authenticated/vendor/orders'
      path: '/vendor/orders'
      fullPath: '/vendor/orders'
      preLoaderRoute: typeof AuthenticatedVendorOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendor/messages': {
      id: '/_authenticated/vendor/messages'
      path: '/vendor/messages'
      fullPath: '/vendor/messages'
      preLoaderRoute: typeof AuthenticatedVendorMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendor/menu': {
      id: '/_authenticated/vendor/menu'
      path: '/vendor/menu'
      fullPath: '/vendor/menu'
      preLoaderRoute: typeof AuthenticatedVendorMenuRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendor/earnings': {
      id: '/_authenticated/vendor/earnings'
      path: '/vendor/earnings'
      fullPath: '/vendor/earnings'
      preLoaderRoute: typeof AuthenticatedVendorEarningsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendor/dashboard': {
      id: '/_authenticated/vendor/dashboard'
      path: '/vendor/dashboard'
      fullPath: '/vendor/dashboard'
      preLoaderRoute: typeof AuthenticatedVendorDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rider/earnings': {
      id: '/_authenticated/rider/earnings'
      path: '/rider/earnings'
      fullPath: '/rider/earnings'
      preLoaderRoute: typeof AuthenticatedRiderEarningsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rider/documents': {
      id: '/_authenticated/rider/documents'
      path: '/rider/documents'
      fullPath: '/rider/documents'
      preLoaderRoute: typeof AuthenticatedRiderDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rider/dashboard': {
      id: '/_authenticated/rider/dashboard'
      path: '/rider/dashboard'
      fullPath: '/rider/dashboard'
      preLoaderRoute: typeof AuthenticatedRiderDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rider/available': {
      id: '/_authenticated/rider/available'
      path: '/rider/available'
      fullPath: '/rider/available'
      preLoaderRoute: typeof AuthenticatedRiderAvailableRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/$orderId': {
      id: '/_authenticated/orders/$orderId'
      path: '/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof AuthenticatedOrdersOrderIdRouteImport
      parentRoute: typeof AuthenticatedOrdersRoute
    }
    '/_authenticated/chats/$vendorId': {
      id: '/_authenticated/chats/$vendorId'
      path: '/chats/$vendorId'
      fullPath: '/chats/$vendorId'
      preLoaderRoute: typeof AuthenticatedChatsVendorIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/webshop': {
      id: '/_authenticated/admin/webshop'
      path: '/admin/webshop'
      fullPath: '/admin/webshop'
      preLoaderRoute: typeof AuthenticatedAdminWebshopRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/success': {
      id: '/_authenticated/admin/success'
      path: '/admin/success'
      fullPath: '/admin/success'
      preLoaderRoute: typeof AuthenticatedAdminSuccessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/stores': {
      id: '/_authenticated/admin/stores'
      path: '/admin/stores'
      fullPath: '/admin/stores'
      preLoaderRoute: typeof AuthenticatedAdminStoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/store-groups': {
      id: '/_authenticated/admin/store-groups'
      path: '/admin/store-groups'
      fullPath: '/admin/store-groups'
      preLoaderRoute: typeof AuthenticatedAdminStoreGroupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/sales': {
      id: '/_authenticated/admin/sales'
      path: '/admin/sales'
      fullPath: '/admin/sales'
      preLoaderRoute: typeof AuthenticatedAdminSalesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/riders': {
      id: '/_authenticated/admin/riders'
      path: '/admin/riders'
      fullPath: '/admin/riders'
      preLoaderRoute: typeof AuthenticatedAdminRidersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/reviews': {
      id: '/_authenticated/admin/reviews'
      path: '/admin/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AuthenticatedAdminReviewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/profile': {
      id: '/_authenticated/admin/profile'
      path: '/admin/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AuthenticatedAdminProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/prep-times': {
      id: '/_authenticated/admin/prep-times'
      path: '/admin/prep-times'
      fullPath: '/admin/prep-times'
      preLoaderRoute: typeof AuthenticatedAdminPrepTimesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/performance': {
      id: '/_authenticated/admin/performance'
      path: '/admin/performance'
      fullPath: '/admin/performance'
      preLoaderRoute: typeof AuthenticatedAdminPerformanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/payouts-orders': {
      id: '/_authenticated/admin/payouts-orders'
      path: '/admin/payouts-orders'
      fullPath: '/admin/payouts-orders'
      preLoaderRoute: typeof AuthenticatedAdminPayoutsOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/payouts': {
      id: '/_authenticated/admin/payouts'
      path: '/admin/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AuthenticatedAdminPayoutsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/operations': {
      id: '/_authenticated/admin/operations'
      path: '/admin/operations'
      fullPath: '/admin/operations'
      preLoaderRoute: typeof AuthenticatedAdminOperationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/offers': {
      id: '/_authenticated/admin/offers'
      path: '/admin/offers'
      fullPath: '/admin/offers'
      preLoaderRoute: typeof AuthenticatedAdminOffersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/menu': {
      id: '/_authenticated/admin/menu'
      path: '/admin/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof AuthenticatedAdminMenuRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/marketing': {
      id: '/_authenticated/admin/marketing'
      path: '/admin/marketing'
      fullPath: '/admin/marketing'
      preLoaderRoute: typeof AuthenticatedAdminMarketingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/invoices': {
      id: '/_authenticated/admin/invoices'
      path: '/admin/invoices'
      fullPath: '/admin/invoices'
      preLoaderRoute: typeof AuthenticatedAdminInvoicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/invoice-settings': {
      id: '/_authenticated/admin/invoice-settings'
      path: '/admin/invoice-settings'
      fullPath: '/admin/invoice-settings'
      preLoaderRoute: typeof AuthenticatedAdminInvoiceSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/holiday-hours': {
      id: '/_authenticated/admin/holiday-hours'
      path: '/admin/holiday-hours'
      fullPath: '/admin/holiday-hours'
      preLoaderRoute: typeof AuthenticatedAdminHolidayHoursRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/general': {
      id: '/_authenticated/admin/general'
      path: '/admin/general'
      fullPath: '/admin/general'
      preLoaderRoute: typeof AuthenticatedAdminGeneralRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/financing': {
      id: '/_authenticated/admin/financing'
      path: '/admin/financing'
      fullPath: '/admin/financing'
      preLoaderRoute: typeof AuthenticatedAdminFinancingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/documents': {
      id: '/_authenticated/admin/documents'
      path: '/admin/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AuthenticatedAdminDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/devices': {
      id: '/_authenticated/admin/devices'
      path: '/admin/devices'
      fullPath: '/admin/devices'
      preLoaderRoute: typeof AuthenticatedAdminDevicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/delivery': {
      id: '/_authenticated/admin/delivery'
      path: '/admin/delivery'
      fullPath: '/admin/delivery'
      preLoaderRoute: typeof AuthenticatedAdminDeliveryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/customers': {
      id: '/_authenticated/admin/customers'
      path: '/admin/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AuthenticatedAdminCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/customer-insights': {
      id: '/_authenticated/admin/customer-insights'
      path: '/admin/customer-insights'
      fullPath: '/admin/customer-insights'
      preLoaderRoute: typeof AuthenticatedAdminCustomerInsightsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/banking': {
      id: '/_authenticated/admin/banking'
      path: '/admin/banking'
      fullPath: '/admin/banking'
      preLoaderRoute: typeof AuthenticatedAdminBankingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/ads': {
      id: '/_authenticated/admin/ads'
      path: '/admin/ads'
      fullPath: '/admin/ads'
      preLoaderRoute: typeof AuthenticatedAdminAdsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/vendor/$slug/item/$itemId': {
      id: '/vendor/$slug/item/$itemId'
      path: '/item/$itemId'
      fullPath: '/vendor/$slug/item/$itemId'
      preLoaderRoute: typeof VendorSlugItemItemIdRouteImport
      parentRoute: typeof VendorSlugRoute
    }
    '/_authenticated/vendor/messages/$conversationId': {
      id: '/_authenticated/vendor/messages/$conversationId'
      path: '/$conversationId'
      fullPath: '/vendor/messages/$conversationId'
      preLoaderRoute: typeof AuthenticatedVendorMessagesConversationIdRouteImport
      parentRoute: typeof AuthenticatedVendorMessagesRoute
    }
  }
}

interface AuthenticatedOrdersRouteChildren {
  AuthenticatedOrdersOrderIdRoute: typeof AuthenticatedOrdersOrderIdRoute
}

const AuthenticatedOrdersRouteChildren: AuthenticatedOrdersRouteChildren = {
  AuthenticatedOrdersOrderIdRoute: AuthenticatedOrdersOrderIdRoute,
}

const AuthenticatedOrdersRouteWithChildren =
  AuthenticatedOrdersRoute._addFileChildren(AuthenticatedOrdersRouteChildren)

interface AuthenticatedWalletRouteChildren {
  AuthenticatedWalletRequestRoute: typeof AuthenticatedWalletRequestRoute
  AuthenticatedWalletSendRoute: typeof AuthenticatedWalletSendRoute
  AuthenticatedWalletTopUpRoute: typeof AuthenticatedWalletTopUpRoute
}

const AuthenticatedWalletRouteChildren: AuthenticatedWalletRouteChildren = {
  AuthenticatedWalletRequestRoute: AuthenticatedWalletRequestRoute,
  AuthenticatedWalletSendRoute: AuthenticatedWalletSendRoute,
  AuthenticatedWalletTopUpRoute: AuthenticatedWalletTopUpRoute,
}

const AuthenticatedWalletRouteWithChildren =
  AuthenticatedWalletRoute._addFileChildren(AuthenticatedWalletRouteChildren)

interface AuthenticatedVendorMessagesRouteChildren {
  AuthenticatedVendorMessagesConversationIdRoute: typeof AuthenticatedVendorMessagesConversationIdRoute
}

const AuthenticatedVendorMessagesRouteChildren: AuthenticatedVendorMessagesRouteChildren =
  {
    AuthenticatedVendorMessagesConversationIdRoute:
      AuthenticatedVendorMessagesConversationIdRoute,
  }

const AuthenticatedVendorMessagesRouteWithChildren =
  AuthenticatedVendorMessagesRoute._addFileChildren(
    AuthenticatedVendorMessagesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAddressesRoute: typeof AuthenticatedAddressesRoute
  AuthenticatedBookRoute: typeof AuthenticatedBookRoute
  AuthenticatedCartRoute: typeof AuthenticatedCartRoute
  AuthenticatedDiscoverRoute: typeof AuthenticatedDiscoverRoute
  AuthenticatedGroceriesRoute: typeof AuthenticatedGroceriesRoute
  AuthenticatedHelpRoute: typeof AuthenticatedHelpRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRouteWithChildren
  AuthenticatedPaymentMethodsRoute: typeof AuthenticatedPaymentMethodsRoute
  AuthenticatedPersonalInfoRoute: typeof AuthenticatedPersonalInfoRoute
  AuthenticatedReferralsRoute: typeof AuthenticatedReferralsRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRouteWithChildren
  AuthenticatedAdminAdsRoute: typeof AuthenticatedAdminAdsRoute
  AuthenticatedAdminBankingRoute: typeof AuthenticatedAdminBankingRoute
  AuthenticatedAdminCustomerInsightsRoute: typeof AuthenticatedAdminCustomerInsightsRoute
  AuthenticatedAdminCustomersRoute: typeof AuthenticatedAdminCustomersRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminDeliveryRoute: typeof AuthenticatedAdminDeliveryRoute
  AuthenticatedAdminDevicesRoute: typeof AuthenticatedAdminDevicesRoute
  AuthenticatedAdminDocumentsRoute: typeof AuthenticatedAdminDocumentsRoute
  AuthenticatedAdminFinancingRoute: typeof AuthenticatedAdminFinancingRoute
  AuthenticatedAdminGeneralRoute: typeof AuthenticatedAdminGeneralRoute
  AuthenticatedAdminHolidayHoursRoute: typeof AuthenticatedAdminHolidayHoursRoute
  AuthenticatedAdminInvoiceSettingsRoute: typeof AuthenticatedAdminInvoiceSettingsRoute
  AuthenticatedAdminInvoicesRoute: typeof AuthenticatedAdminInvoicesRoute
  AuthenticatedAdminMarketingRoute: typeof AuthenticatedAdminMarketingRoute
  AuthenticatedAdminMenuRoute: typeof AuthenticatedAdminMenuRoute
  AuthenticatedAdminOffersRoute: typeof AuthenticatedAdminOffersRoute
  AuthenticatedAdminOperationsRoute: typeof AuthenticatedAdminOperationsRoute
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminPayoutsRoute: typeof AuthenticatedAdminPayoutsRoute
  AuthenticatedAdminPayoutsOrdersRoute: typeof AuthenticatedAdminPayoutsOrdersRoute
  AuthenticatedAdminPerformanceRoute: typeof AuthenticatedAdminPerformanceRoute
  AuthenticatedAdminPrepTimesRoute: typeof AuthenticatedAdminPrepTimesRoute
  AuthenticatedAdminProfileRoute: typeof AuthenticatedAdminProfileRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminReviewsRoute: typeof AuthenticatedAdminReviewsRoute
  AuthenticatedAdminRidersRoute: typeof AuthenticatedAdminRidersRoute
  AuthenticatedAdminSalesRoute: typeof AuthenticatedAdminSalesRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminStoreGroupsRoute: typeof AuthenticatedAdminStoreGroupsRoute
  AuthenticatedAdminStoresRoute: typeof AuthenticatedAdminStoresRoute
  AuthenticatedAdminSuccessRoute: typeof AuthenticatedAdminSuccessRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminWebshopRoute: typeof AuthenticatedAdminWebshopRoute
  AuthenticatedChatsVendorIdRoute: typeof AuthenticatedChatsVendorIdRoute
  AuthenticatedRiderAvailableRoute: typeof AuthenticatedRiderAvailableRoute
  AuthenticatedRiderDashboardRoute: typeof AuthenticatedRiderDashboardRoute
  AuthenticatedRiderDocumentsRoute: typeof AuthenticatedRiderDocumentsRoute
  AuthenticatedRiderEarningsRoute: typeof AuthenticatedRiderEarningsRoute
  AuthenticatedVendorDashboardRoute: typeof AuthenticatedVendorDashboardRoute
  AuthenticatedVendorEarningsRoute: typeof AuthenticatedVendorEarningsRoute
  AuthenticatedVendorMenuRoute: typeof AuthenticatedVendorMenuRoute
  AuthenticatedVendorMessagesRoute: typeof AuthenticatedVendorMessagesRouteWithChildren
  AuthenticatedVendorOrdersRoute: typeof AuthenticatedVendorOrdersRoute
  AuthenticatedVendorProfileRoute: typeof AuthenticatedVendorProfileRoute
  AuthenticatedVendorShopsRoute: typeof AuthenticatedVendorShopsRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAddressesRoute: AuthenticatedAddressesRoute,
  AuthenticatedBookRoute: AuthenticatedBookRoute,
  AuthenticatedCartRoute: AuthenticatedCartRoute,
  AuthenticatedDiscoverRoute: AuthenticatedDiscoverRoute,
  AuthenticatedGroceriesRoute: AuthenticatedGroceriesRoute,
  AuthenticatedHelpRoute: AuthenticatedHelpRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRouteWithChildren,
  AuthenticatedPaymentMethodsRoute: AuthenticatedPaymentMethodsRoute,
  AuthenticatedPersonalInfoRoute: AuthenticatedPersonalInfoRoute,
  AuthenticatedReferralsRoute: AuthenticatedReferralsRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRouteWithChildren,
  AuthenticatedAdminAdsRoute: AuthenticatedAdminAdsRoute,
  AuthenticatedAdminBankingRoute: AuthenticatedAdminBankingRoute,
  AuthenticatedAdminCustomerInsightsRoute:
    AuthenticatedAdminCustomerInsightsRoute,
  AuthenticatedAdminCustomersRoute: AuthenticatedAdminCustomersRoute,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminDeliveryRoute: AuthenticatedAdminDeliveryRoute,
  AuthenticatedAdminDevicesRoute: AuthenticatedAdminDevicesRoute,
  AuthenticatedAdminDocumentsRoute: AuthenticatedAdminDocumentsRoute,
  AuthenticatedAdminFinancingRoute: AuthenticatedAdminFinancingRoute,
  AuthenticatedAdminGeneralRoute: AuthenticatedAdminGeneralRoute,
  AuthenticatedAdminHolidayHoursRoute: AuthenticatedAdminHolidayHoursRoute,
  AuthenticatedAdminInvoiceSettingsRoute:
    AuthenticatedAdminInvoiceSettingsRoute,
  AuthenticatedAdminInvoicesRoute: AuthenticatedAdminInvoicesRoute,
  AuthenticatedAdminMarketingRoute: AuthenticatedAdminMarketingRoute,
  AuthenticatedAdminMenuRoute: AuthenticatedAdminMenuRoute,
  AuthenticatedAdminOffersRoute: AuthenticatedAdminOffersRoute,
  AuthenticatedAdminOperationsRoute: AuthenticatedAdminOperationsRoute,
  AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRoute,
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
  AuthenticatedAdminPayoutsRoute: AuthenticatedAdminPayoutsRoute,
  AuthenticatedAdminPayoutsOrdersRoute: AuthenticatedAdminPayoutsOrdersRoute,
  AuthenticatedAdminPerformanceRoute: AuthenticatedAdminPerformanceRoute,
  AuthenticatedAdminPrepTimesRoute: AuthenticatedAdminPrepTimesRoute,
  AuthenticatedAdminProfileRoute: AuthenticatedAdminProfileRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminReviewsRoute: AuthenticatedAdminReviewsRoute,
  AuthenticatedAdminRidersRoute: AuthenticatedAdminRidersRoute,
  AuthenticatedAdminSalesRoute: AuthenticatedAdminSalesRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminStoreGroupsRoute: AuthenticatedAdminStoreGroupsRoute,
  AuthenticatedAdminStoresRoute: AuthenticatedAdminStoresRoute,
  AuthenticatedAdminSuccessRoute: AuthenticatedAdminSuccessRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminWebshopRoute: AuthenticatedAdminWebshopRoute,
  AuthenticatedChatsVendorIdRoute: AuthenticatedChatsVendorIdRoute,
  AuthenticatedRiderAvailableRoute: AuthenticatedRiderAvailableRoute,
  AuthenticatedRiderDashboardRoute: AuthenticatedRiderDashboardRoute,
  AuthenticatedRiderDocumentsRoute: AuthenticatedRiderDocumentsRoute,
  AuthenticatedRiderEarningsRoute: AuthenticatedRiderEarningsRoute,
  AuthenticatedVendorDashboardRoute: AuthenticatedVendorDashboardRoute,
  AuthenticatedVendorEarningsRoute: AuthenticatedVendorEarningsRoute,
  AuthenticatedVendorMenuRoute: AuthenticatedVendorMenuRoute,
  AuthenticatedVendorMessagesRoute:
    AuthenticatedVendorMessagesRouteWithChildren,
  AuthenticatedVendorOrdersRoute: AuthenticatedVendorOrdersRoute,
  AuthenticatedVendorProfileRoute: AuthenticatedVendorProfileRoute,
  AuthenticatedVendorShopsRoute: AuthenticatedVendorShopsRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface VendorSlugRouteChildren {
  VendorSlugItemItemIdRoute: typeof VendorSlugItemItemIdRoute
}

const VendorSlugRouteChildren: VendorSlugRouteChildren = {
  VendorSlugItemItemIdRoute: VendorSlugItemItemIdRoute,
}

const VendorSlugRouteWithChildren = VendorSlugRoute._addFileChildren(
  VendorSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VendorSlugRoute: VendorSlugRouteWithChildren,
  ApiWebhooksPaystackRoute: ApiWebhooksPaystackRoute,
  ApiWebhooksStripeRoute: ApiWebhooksStripeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
